apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/svmt/eks-blueprints-add-ons
    path: 'kustomize'
    targetRevision: main
